### ISSUE TITLE
Rework workspace API

### ISSUE THREAD

**Issue by marceljaehn** [openorg-software/openrqm-server#22]
**Rework methods:**
- addAccessGroupToWorkspace(workspaceId, accessGroupId, permissions);
- addUserToWorkspace(workspaceId, userId, permissions);
- deleteAccessGroupOfWorkspace(workspaceId, accessGroupId);
- deleteUserOfWorkspace(workspaceId, userId);
- getAccessGroupsOfWorkspace(workspaceId);
- getUsersOfWorkspace(workspaceId);

**Remove methods:**
- patchAccessGroupOfWorkspace : access groups should be patched through accessgroup API
- patchUserOfWorkspace : users should be patched through user API

**Add methods:**
- setAccessGroupPermissionsForWorkspace(workspaceId, accessGroupId, permissions)
- setUserPermissionsForWorkspace(workspaceId, userId, permissions)

**Comment by benjaminSchilling33** [comment]
See https://github.com/openrqm/openrqm-docs/commit/9ddba88bb37b83ff0b84d407042f4b77e5b23bc0
