### ISSUE TITLE
Rework accessgroup API

### ISSUE THREAD

**Issue by marceljaehn** [openorg-software/openrqm-server#23]
**Rework methods:**
- addUserToAccessGroup(accessgroupId, userId);
- deleteUserOfAccessGroup(accessgroupId, userId);
- getAccessgroup(accessgroupId);
- getUsersOfAccessGroup(accessgroupId);
- patchUserOfAccessGroup : should be made through the user API

**Comment by benjaminSchilling33** [comment]
See https://github.com/openrqm/openrqm-docs/commit/9ddba88bb37b83ff0b84d407042f4b77e5b23bc0
